### PR TITLE
Extensiongui

### PR DESCRIPTION
**Pull request by caver456**
options in the extension GUI are working, by being passed from chrome.storage.sync to background.js to wrapper.py; need to discuss the direction, and do more QA if it looks good

### CODE REVIEW

**Comment by mtjacobs** [comment]
I'd really like to trim the language down a bit, but more importantly change the defaults to pull everything.  I think the default restrictions are too tightly tied to your SAR use case, and since they persist in storage, they should be easy to set and forget on team machines.  Thoughts?

Didn't realize that Firefox supports the chrome.* namespace.  That's convenient.

**Comment by caver456** [comment]
I plan to reduce the wording and use some styles in popup.js to get it to
look and fit the same in FF as in chrome tonight.

I do think the defaults are pretty important, defaulting to
no-filter-at-all  would largely negate the benefits of having them
available, as many or most users would not know to click the extension icon
even if the dialog title text says to do so; even if they do, the first
import, if completely unfiltered, could potentially tie up the computer
for  10+minutes.  How about optionally setting defaults in config.py of the
extension?  That would allow completely unfiltered defaults if no relevant
settings exist.  Of course then you would need to get that from .py back
into storage or javascript.

**Comment by caver456** [comment]
made a commit using pure-css popup for the wording; it is not clean yet -
just a concept.  I took code from here:
https://codepen.io/imprakash/pen/GgNMXO - I don't see any indication of
licensing issues.

**Comment by caver456** [comment]
It would be nice if you could open the extension popup programmatically on
the first call to GPSIO import... looks like that cannot be done
https://stackoverflow.com/questions/10479679/how-can-i-open-my-extensions-pop-up-with-javascript

Another option would be to have sar-defaults vs other-defaults based on the
url of the currently open page... still a question of passing defaults
between js and py.

**Comment by mtjacobs** [comment]
Do you think that both the recency and file size checks are necessary to prevent lockup when importing a large dataset?  I agree that's a good thing to protect the user against, particularly with a message getting passed back to the UI that the import was from a limited subset.

**Comment by caver456** [comment]
good question, I was just speculating, but also did notice that some huge
files were among the most recent.  The last time that one of the guys used
his GPS was a bike tour in France... that locked up the computer for
probably 15 minutes (half of that being the boot time, separate topic,
which we potentially addressed in other emails).  So, probably
last-24-hours would not need the size filter, but, most-recent-n probably
would.  I can definitely understand why the size filter would make complete
sense for SAR but could be inappropriate for non-SAR.   Regardless, for all
users, it would keep the computer from seemingly freezing on the initial
import. If the initial import is filtered too rigorously, at least it will
be quick, in which case hopefully the title note resolves things; an
underfiltered or unfiltered initial import could lock up the computer for a
while.  At a broader level I agree that it's pretty odd (or even "bad
design") for a browser extension to apply heavy filtering out of the box
without the user specifically telling it to do so, but, I still feel that
heavy filtering out of the box, including on the very first import, is
necessary for SAR.  Somewhere there is a happy middle ground.  A possible
compromise: maybe the extension could apply one set of detaults if the
sender is 'sartopo' and another set of defaults for everything else.  Or we
could pursue the config file possibilities some more.

**Comment by mtjacobs** [comment]
Changing the settings based on the site being communicated with would be awkward, since there's a single extension / popup window across all active sites.

What do you think about keeping the size filter as a default but dropping the recency filter, or at least setting it to 72 hours?

**Comment by caver456** [comment]
72 hours and 100kb seems like a good compromise.  I will set that up
tonight or soon.

On Jan 5, 2018 11:50 AM, "Matt Jacobs" <notifications@github.com> wrote:

Changing the settings based on the site being communicated with would be
awkward, since there's a single extension / popup window across all active
sites.

What do you think about keeping the size filter as a default but dropping
the recency filter, or at least setting it to 72 hours?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mtjacobs/gpsio/pull/7#issuecomment-355648928>, or mute
the thread

**Comment by caver456** [comment]
I think this covers it - set defaults as we discussed, and cleaned up the popup; tested in chrome and firefox.

**Comment by caver456** [comment]
new gpsio commit, posted on the pull request thread online, not sure if
that gets sent out.  Anyway, hopefully that should address everything, see
what you think.

**Comment by caver456** [comment]
Also I did not change the version number in the manifest.

**Comment by caver456** [comment]
Excellent, I will make the video and docs tonight or whenever it is
available from the chrome web store.  Also seems like the right way to go
is to put the docs on the extension page instead of the caltopo help page.

**Pull request merged**
